import React from 'react'
import { Link } from 'react-router-dom'
import Navbar from '../Navbar'

const Terms = () => (
    <section className="container-fluid">
        <Navbar />
        <div className="row terms-section">
            <div className="col-12 py-3">
                <h1>Terms & Conditions</h1>
            </div>
            <div className="col-12">
                <p className="pl-4">Effective Date: <i>Nov. 1, 2020</i></p>
                <ol className="pl-3">
                    <li>
                        <h5><b>Introduction</b></h5>
                            
                        <p>Welcome to <b>Would Bee</b>.</p>
                            
                        <p><strong>Apptivism Private Limited</strong> ("Company", "we", "our", "us") operates <Link to="/">https://wouldbee.com/</Link>, companion mobile applications on Android and iOS platforms, and service on Telegram and WhatsApp messengers (together or individually "Services", "Service", or "Matrimony Service").</p>

                        <p>These Terms ("Terms", "Terms of Service") govern your use of our <strong>service</strong>.</p>

                        <p>In order to use our service, you must Register as a member of our service and agree to be bound by These Terms of Service ("Terms", "Terms of Service", "Agreement"). If you wish to become a Member and communicate with other Members and make use of the service ("Service"), read these Terms of Use and follow the instructions in the Registration process. This Agreement sets out the legally binding terms for your membership. This Agreement may be modified by us from time to time effective upon notice to you as a Member. Whenever there is a change in the Terms of Use, we will intimate you of such change. Your continued use of the Site pursuant to such change will constitute deemed acceptance of such changes.</p>
                        <p><b>Eligibility</b></p>
                        <p>You must be at least 18 years of age or over to Register as a member of our service. Membership to the Site is void where prohibited. Your use of our Service represents and warrants that you have the right, authority, and capacity to enter into this Agreement and to abide by all of the terms and conditions of this Agreement. This site is not meant to encourage and/or promote illicit sexual relationships or extra marital affairs. If we discover or become aware that any member is using our Service to promote or engage or indulge in illicit sexual relations or extra marital affairs, his/her membership will be terminated forthwith without any refund and without any liability to the company. Company's discretion to terminate shall be final and binding.</p>
                            
                        <p><b>Term</b></p>
                        <p>This Agreement will remain in full force and effect while you use the service. You may terminate your membership at any time, for any reason by informing us in writing to terminate your Membership. In the event you terminate your membership, you will not be entitled to a refund of any unutilized subscription fees. We may terminate your access to the Service and/or your membership for any reason which shall be effective upon sending notice of termination to you at the email address/phone number you provide in your application for membership or such other email address/phone number as you may later provide to us. If the company terminates your membership because of your breaching the Agreement, you will not be entitled to any refund of any unused Subscription fees.</p>
                            
                        <p><b>Non-Commercial Use by Members</b></p>
                        <p>Our services are meant for the personal use of individual members only, and must not be used in connection with any commercial endeavors. This includes providing links to other websites, whether deemed competitive to our service or otherwise. Organizations, companies, and/or businesses may not become Members of our Service and should not use the Service for any purpose. Illegal and/or unauthorized uses of the Service, including unauthorized framing of or linking to the Site will be investigated, and appropriate legal action will be taken, including without limitation, civil, criminal, and injunctive redress.</p>
                            
                        <p><b>Other Terms of Use by Members</b></p>
                        <p>You may not engage in advertising to, or solicitation of, other Members to buy or sell any products or services through the Service. You will not transmit any chain letters or junk email to other Members of the service. Although we cannot monitor the conduct of our Members outside the service, it is also a violation of this Agreement to use any information obtained from the Service in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to any Member without their prior explicit consent. In order to protect our service and/or our Members from any abuse/misuse, we reserves the right to restrict the number of communications/profile contacts and responses/emails which a Member may send to other Member(s) in any 24-hour period to a number which the company deems appropriate in its sole discretion. You will not send any messages to other Members that are obscene, lewd, licentious, and defamatory, promote hatred and/or are racial or abusive in any manner. Transmission of any such messages shall constitute a breach of this Agreement and we Shall be entitled to terminate your membership forthwith. We reserve the right to screen messages that you may send to other Member(s) and also regulate the number of your chat sessions in its sole discretion. You may not use any automated processes, including IRC Bots, EXE's, CGI or any other programs/scripts to view content on or communicate/contact/respond/interact with Would Bee Service and/or its Members</p>
                            
                        <p><b>Content Posted on the Site</b></p>
                        <p>We own and retain all proprietary rights, including without limitation, all intellectual property rights in the wouldbee.com Site and the companion Services. The Site/App contains the copyrighted material, trademarks, and other proprietary information of the company, and its licensors. Except for that information which is in the public domain or for which you have been given express permission by us, you may not copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information. All lawful, legal and non-objectionable messages (in the sole discretion of the company), content and/or other information, content or material that you post on the forum boards shall become the property of the company. We reserve the right to scrutinize all such information, content and/or material posted on the forum boards and shall have the exclusive right to either remove, edit and/or display such information, material and/or content.</p>
                            
                        <p>You understand and agree that we may delete any content, messages, photos or profiles (collectively, "Content") that in the sole judgment of the company violates this Agreement or which might be offensive, illegal, defamatory, obscene, libelous, or that might violate the rights, harm, or threaten the safety of our other Members.</p>
                            
                        <p>You are solely responsible for the Content that you publish or display ("post") on our Service, or transmit to other Members of our service. We reserve the right to verify the authenticity of Content posted on the Site. In exercising this right, we may ask you to provide any documentary or other form of evidence supporting the Content you post on the Site. If you fail to produce such evidence, or if such evidence does not in the reasonable opinion of the company establish or justify the claim, we may, in our sole discretion, terminate your Membership without a refund of your subscription fees.</p>
                            
                        <p>By posting Content to any public area of our service, you automatically grant, and you represent and warrant that you have the right to grant, to us, and other service Members, an irrevocable, perpetual, non-exclusive, fully-paid, worldwide license to use, copy, perform, display, and distribute such information and content and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sublicenses of the foregoing.</p>
                        <p>The following is a partial list of the kind of Content that is illegal or prohibited on our Service. We will investigate and take appropriate legal action in its sole discretion against anyone who violates this provision, including without limitation, removing the offending communication from the Service and the Site and terminating the Membership of such violators without a refund. It includes (but is not limited to) Content that: Harasses or advocates harassment of another person; Involves the transmission of "junk mail", "chain letters," or unsolicited mass mailing or "spamming"; Promotes information that the person posting it is aware that it is false, misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous; Promotes an illegal or unauthorized copy of another person's copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files; Contains restricted or password only access pages, or hidden pages or images (those not linked to or from another accessible page) ; Displays pornographic or sexually explicit material of any kind; Provides material that exploits people under the age of 18 years in a sexual or violent manner, or solicits personal information from anyone under the age of 18 years; Provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses; Solicits passwords or personal identifying information for commercial or unlawful purposes from other users / Members; and Engages in commercial activities and/or sales without the prior written consent from us such as contests, sweepstakes, barter, advertising, and pyramid schemes. Encourages, invites or solicits extra marital affairs.</p>

                        <p>Newly created profiles will be checked for correctness and will be immediately activated after quality verification by us. We reserve the rights to discontinue, deactivate, or terminate profile if the profile in terms of bad manners and the profile contents are not acceptable if it contains violent language or wrong material. You are only liable for your connections with other members through our service.</p>

                        <p>Free membership to the services offered by us is for limited time. We reserves right to discontinue free membership at any time. Members agree that they are legally eligible to get married as far as the age or their current marital status is concerned. We will not be responsible for misuse of any facility/service it provides, which is in violation to the local government laws. Every member submitting his/her matrimonial profile is required to give all the facts essential for establishing a marital relation. Concealing facts relevant to marriage could result in loss or damage to any individual and for which, the company cannot be held responsible in any which way. The company in no way guarantees the genuineness of the information provided by its members.</p>
                        <p>Members will not have any claim against the company for any time delay in posting their information into wouldbee.com website or its companion service due to any reasons.</p>

                        <p>We are not liable for damages caused due to incorrectness of the information provided by its members regarding the religion, caste or creed or any other personal information. If the members’ profile is deemed to be unfit, the company has the right to delete, alter or refuse the same at any point of time without any notice.</p>
                            
                        <p>We cannot be held responsible for any loss or damage resulting from discontinuation of the service. We will also not be responsible for any damage caused due to others accessing members profile. We cannot guarantee that you as an applicant will receive responses and hence cannot be held responsible for no replies. In this case, we cannot give any refunds or credits.</p>

                        <p>You must use our Service in a manner consistent with any and all applicable local, state, and federal laws and regulations. You are not permitted to create multiple profiles. If we find out that you have created multiple profiles, your membership will be liable to be terminated forthwith without any refund of subscription fees. If at any time we are of the view in its sole discretion that your profile contains any information or material or content which is objectionable, unlawful or illegal, we have the right in our sole discretion to either forthwith terminate your membership without refund of your subscription fees or delete such objectionable, illegal or unlawful information.</p>

                        <p><b>Copyright Policy</b></p>
                        <p>You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. Without limiting the foregoing, if you believe that your work has been copied and posted on the Site through our Service in a way that constitutes copyright infringement, please provide our Copyright Agent with the following information: an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; a description of the copyrighted work that you claim has been infringed; a description of where the material that you claim is infringing is located on the Site; your address, telephone number, and email address; a written statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and where applicable a copy of the registration certificate proving registration of copyright or any other applicable intellectual property right; a statement by you, made under penalty of perjury, that the above information in your Notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf. Our Copyright Agent for Notice of claims of copyright infringement can be reached by writing to the Jaipur address located under the Help/Contact section on the site.</p>
                            
                        <p><b>Member Disputes</b></p>
                        <p>You are solely responsible for your interactions with other Members of our service. We reserve the right, but has no obligation, to monitor disputes between you and other Members.</p>

                        <p>Privacy Use of our Service is governed by our <Link to="/privacy">Privacy Policy</Link>.</p>

                        <p><b>Disclaimers</b></p>
                        <p>We are not responsible for any incorrect or inaccurate Content posted on the Site or in connection with the wouldbee.com Service, whether caused by using the Service, Members or by any of the equipment or programming associated with or utilized in the Service, nor for the conduct of any user and/or Member of our Service whether online or offline. We assumes no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, user and/or Member communications. We are not responsible for any problems or technical malfunction of any telephone network or lines, computer on-line-systems, servers or providers, computer equipment, software, failure of email or players on account of technical problems or traffic congestion on the Internet or at any website or combination thereof, including injury or damage to users and/or Members or to any other person's computer related to or resulting from participating or downloading materials in connection with our Service and/or in connection with any companion Service. Under no circumstances will we be responsible for any loss or damage to any person resulting from anyone's use of the Site or the Service and/or any Content posted on our Service or transmitted to our Members. The exchange of profile(s) through or by our service Should not in any way be construed as any offer and/or recommendation from/by us. We Shall not be responsible for any loss or damage to any individual arising out of, or subsequent to, relations established pursuant to the use of our service. The Site and the Service are provided "AS-IS AVAILABLE BASIS" and we expressly disclaim any warranty of fitness for a particular purpose or non-infringement. We cannot guarantee and do not promise any specific results from use of our Service.</p>

                        <p><b>Limitation on Liability</b></p>
                        <p>Except in jurisdictions where such provisions are restricted, in no event will we be liable to you or any third person for any indirect, consequential, exemplary, incidental, special or punitive damages, including also lost profits arising from your use of our Service, even if we have been advised of the possibility of such damages. Notwithstanding anything to the contrary contained herein, wouldbee.com, our apps, and our Telegram messenger bot, liability to you for any cause whatsoever, and regardless of the form of the action, will at all times be limited to the amount paid, if any, by you to us, for the Service during the term of membership.</p>
                            
                        <p><b>Disputes</b></p>
                        <p>If there is any dispute about or involving the Site and/or the Service, by using the Service, you agree that the dispute will be governed by the laws of India. You agree to the exclusive jurisdiction to the courts of Jaipur, Rajasthan, India.</p>
                            
                        <p><b>Indemnity</b></p>
                        <p>You agree to indemnify and hold the company, its subsidiaries, directors, affiliates, officers, agents, and other partners and employees, harmless from any loss, liability, claim, or demand, including reasonable attorney's fees, made by any third party due to or arising out of your use of the Service in violation of this Agreement and/or arising from a breach of these Terms of Use and/or any breach of your representations and warranties set forth above.</p>
                            
                        <p><b>Other</b></p>
                        <p>By becoming a Member of the Site/Service, you agree to receive certain specific emails from us. This Agreement, accepted upon use of the Site and further affirmed by becoming a Member of our Service, contains the entire agreement between you and the company regarding the use of the Site and/or the Service. If any provision of this Agreement is held invalid, the remainder of this Agreement shall continue in full force and effect. You are under an obligation to report any misuse or abuse of the Site. If you notice any abuse or misuse of the Site or anything which is in violation of this Agreement, you shall forthwith report such violation to us by writing to Customer Care. On receipt of such complaint, we may investigate such complaint and if necessary may terminate the membership of the Member responsible for such violation abuse or misuse without any refund of subscription fee. Any false complaint made by a Member shall make such Member liable for termination of his/her membership without any refund of the subscription fee. Please contact us with any questions regarding this Agreement.</p>
                        {/* <Link to="/">
                            <button className="btn btn-primary btn-sm mt-4 back-btn" style={{ width: '40%', maxWidth: '200px' }}>Go Back</button>
                        </Link> */}
                            
                    </li>
                </ol>
            </div>
        </div>
    </section>
);

export default Terms;
